# Change baseurl before deploy
baseurl = "https://0065537.xyz"
languageCode = "en-us"
title = "Rabjho"
theme = "hugo-theme-stack"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

[pagination]
pagerSize = 15

[[params.imageProcessing]]
    [cover]
        enabled = false
    [content]
        enabled = false