baseURL = 'https://Rabjho.github.io/Rabjho-Rambles'
languageCode = 'en-us'
title = 'Rabjho Rambles'
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[pagination]
  pagerSize = 20

[params]
  [params.homeInfoParams]
    Title = "Hey! I'm Rabjho, CTF addict with 0-Day Aarhus"
    Content = "Mostly challenge writeups, but might also contain blogs on stuff I develop or other rambles."

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  UseHugoToc = true
  tocopen = false


[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Rabjho"
  
[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/rabjho/"

[taxonomies]
  name = "ctf"
  weight = 10

[menu]
  [[menu.main]]
    identifier = "ctf"
    name = "By CTF"
    url = "/ctf/"
    weight = 15
  [[menu.main]]
    identifier = "tags"
    name = "By tag"
    url = "/tags/"
    weight = 10

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 20

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 30

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"

[outputs]
  home = ["HTML", "RSS", "JSON"]